### ISSUE TITLE
Plans for supporting scala 2.13

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [oleg-py/meow-mtl#15]
Hello,

Just wondering if there's a plan to add support for 2.13.

Thanks.

**Comment by oleg-py** [comment]
@ArulselvanMadhavan sure, I'm mostly waiting for cats-mtl to get updated to 2.13 proper:
https://github.com/typelevel/cats-mtl/issues/128

**Comment by oleg-py** [comment]
0.3.0-M1 for 2.11, 2.12 and 2.13 is on maven central now, based on milestones of cats & cats-effect.
