### ISSUE TITLE
Consider facility to view State as Reader

### ISSUE THREAD

**Issue by benhutchison** [oleg-py/meow-mtl#17]
It can be convenient to allow a `MonadState[F, S]` to serve as an `ApplicativeAsk[F, S]`. We can think of the former constraint as the ability to _read and update_ system state, and the latter as _simply the ability to read it_. If all we need is to read the state, the least privilege principle suggests that a `ApplicativeAsk[F, S]` constraint is preferable.

Traditionally, Reader monad is associated with reading outside configuration. However, IME it also works well to read the domain model of a stateful application (or some part thereof, eg by the lensing techniques already available in this library).

An example of value can be found in the meow-mtl [readme use case](https://github.com/oleg-py/meow-mtl/blame/master/README.md#L34)

This is a proposal to consider an opt-in extra derivation that provides a `ApplicativeAsk[F, S]` should a `MonadState[F, S]` instance be available.

**Comment by oleg-py** [comment]
I think this belongs to [cats-mtl](/typelevel/cats-mtl). I'd like to avoid introducing features that can be done in base library without extra dependencies.

**Comment by benhutchison** [comment]
👍 Makes sense. I was thinking of the analogy to lenses, but categorising by dependencies is probably better.
