### ISSUE TITLE
Make CatsEffectMtlInstances public. 

### ISSUE THREAD

**Issue by Baccata** [oleg-py/meow-mtl#2]
There are cases when I'd like to be able to manually instantiate `RefMonadState`, would you consider lifting the `private` on the `CatsEffectMtlInstances` object ?

**Comment by oleg-py** [comment]
@Baccata sorry for the long delay. Do you need `RefMonadState[F, A]` class typed as such? You can get instance directly, but typed as `MonadState[F, A]` using `ref.runState(ms => ms)`, and I plan to make it simpler given the upcoming changes to better-monadic-for.

**Comment by Baccata** [comment]
> sorry for the long delay

no worries 

> ref.runState(ms => ms)

Good point, I guess I was confusing `runState` with `bracket` of some sort. Thanks !

**Comment by oleg-py** [comment]
There's now `stateInstance` extension method on `ref` in 0.2.0
