### ISSUE TITLE
Where is the `T` of MTL?

### ISSUE THREAD

**Issue by aloiscochard** [oleg-py/meow-mtl#4]
Hey Oleg,

I'm confused about your usage of the term `mtl` in this library name (compared to https://wiki.haskell.org/Monad_Transformer_Library) as I don't really see anything about "transformer" in there?

Am I missing something? What is the motivation for the naming?

Thanks!

**Comment by Zelenya** [comment]
See [Why it's called mtl](https://www.reddit.com/r/scala/comments/90jk2u/mtlstyle_programming/e2qze0c/) by @SystemFW

**Comment by oleg-py** [comment]
Yes, @Zelenya has long beaten me to it :) This project aims to augment `cats-mtl`, so alignment in naming is kinda important as well.

**Comment by aloiscochard** [comment]
Thanks for the reference to the reddit thread, that explains it in great
detail!

**Comment by SystemFw** [comment]
:)
