### ISSUE TITLE
ApplicativeLocal for Monix TaskLocal

### ISSUE THREAD

**Issue by oleg-py** [oleg-py/meow-mtl#5]
`TaskLocal` is pretty cool and should allow us to get an instance of `ApplicativeLocal`, which abstracts over `ReaderT`.

To be done:
- Wait for Monix 3.0.0-RC2 release
- Create a separate module for the project
- Implement :)

**Comment by gvolpe** [comment]
I guess this can be closed now? :)

**Comment by oleg-py** [comment]
Yep, forgot to
