### ISSUE TITLE
Derivations for lenses with multiple fields of the same type

### ISSUE THREAD

**Issue by kubukoz** [oleg-py/meow-mtl#9]
I was wondering what'd happen if I asked meow to generate instances/lenses for a type with same-type fields:

```scala
case class Foo(s: String, y: String)

import com.olegpy.meow.optics.MkLensToType

implicitly[MkLensToType[Foo, String]]
```

Current behavior: the generated lens directs to the `s` field.
Expected behavior: compilation error. The target type is ambiguous and could match either of the class's fields (let alone if any of them was nested), and the current behavior isn't really what a user would expect.

Do you think meow-mtl should make it harder to derive such lenses? If someone really wants to target a field that can't be uniquely determined by its type, maybe force them to pass a symbol with the field's name, or provide the lens themselves?

**Comment by oleg-py** [comment]
Yeah, I know that. Current behavior is depth-first search, which is:
* Relatively fast (compile-time)
* Consistent
* Slightly confusing

The first one is extremely important. My first prototype that did the right thing took 5 minutes to compile one derivation. The second one is important too, I don't want users to have to remember all the edge cases. So, if it's possible to refute values on the same level, but not if one of them is nested deeper, I wouldn't prefer that to the status quo.

Confusion is also not a problem when you use it with stronger types (refined, newtypes, etc.) and not a low-level values without any semantics (number, booleans, strings). That is my recommendation.

Providing good user experience for errors would be a huge challenge, as automatic derivations would just bail out with diverging implicit expansion for instance. Probably would require every instance to be implemented as a macro, but that's not what I'm willing to do right now.
